// SPDX-FileCopyrightText: 2022 Uniontech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: LGPL-3.0-or-later

#define DTK_NAMESPACE Dtk
#define DACCOUNT_NAMESPACE ACCOUNT
#define DTK_ACCOUNT_NAMESPACE DTK_NAMESPACE::DACCOUNT_NAMESPACE

#define DACCOUNTS_USE_NAMESPACE using namespace DTK_ACCOUNT_NAMESPACE;

#define DACCOUNTS_BEGIN_NAMESPACE namespace DTK_NAMESPACE { namespace DACCOUNT_NAMESPACE {

#define DACCOUNTS_END_NAMESPACE }}
